name: Como usar variaveis de ambiente
on: 
  workflow_dispatch
env:
  ENV_WORKFLOW: "Valor workflow"
jobs:
  teste-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor JOB teste-env"
    steps:
      - name: Execucao
        env:
          ENV_ACTION: "Valor ACTION - Execucao"
        run: |
          echo "ENV_WORKFLOW"
          echo "ENV_JOB"
          echo "ENV_ACTION"
